### ISSUE TITLE
Check the font weight , not same as figma

### ISSUE THREAD

**Issue by Mehulna** [Bitovn/social-app-issues#143]
![Screenshot_20240801_112006.jpg](https://github.com/user-attachments/assets/7fae0357-8ba1-4151-9a19-1114f4825d2d)

**Comment by Ayushvayuz** [comment]
![1000113950](https://github.com/user-attachments/assets/93eee8f6-cba2-452e-aab5-5959877a06ad)
![1000113952](https://github.com/user-attachments/assets/662f116c-1ac4-4e3a-ae59-cf300c6e8ec8)
