### ISSUE TITLE
Check the font spacing or weight, doesn't match with figma

### ISSUE THREAD

**Issue by Mehulna** [Bitovn/social-app-issues#3]
![unnamed](https://github.com/Bitovn/social-app-issues/assets/93506258/6ed3f660-6890-4bb7-a6f9-c9727ccfa409)

**Comment by Ayushvayuz** [comment]
@Mehulna i have checked error text's font wasn't matched i have fixed it. Rest of the things are okk. Some times the font of our phone also make some difference. kindly check
