### ISSUE TITLE
Continue button size is not same as Sign in button

### ISSUE THREAD

**Issue by Mehulna** [Bitovn/social-app-issues#5]
![unnamed](https://github.com/Bitovn/social-app-issues/assets/93506258/3d5b71d8-2d95-47b6-8ac7-b3fb6ba67143)

**Comment by Mehulna** [comment]
Check the width and match with sign in button.

**Comment by Ayushvayuz** [comment]
![1000108312](https://github.com/Bitovn/social-app-issues/assets/136789746/50cdfabc-a78e-4f15-a17d-3a4c04747797)
