### ISSUE TITLE
Give proper spacing, looks cluttered 

### ISSUE THREAD

**Issue by Mehulna** [Bitovn/social-app-issues#61]
![unnamed](https://github.com/Bitovn/social-app-issues/assets/93506258/a2eba138-5c23-4b1f-8251-c06a2bc7cded)

**Comment by Ayushvayuz** [comment]
![1000108310](https://github.com/Bitovn/social-app-issues/assets/136789746/4eb74f09-d1f9-45c8-9705-72ee3f3b9d41)
