### ISSUE TITLE
Card Height and width are not same as figma 

### ISSUE THREAD

**Issue by Mehulna** [Bitovn/social-app-issues#68]
![unnamed](https://github.com/Bitovn/social-app-issues/assets/93506258/4b08163e-c283-4490-ac9a-f56f3d0e83b7)

**Comment by Ayushvayuz** [comment]
![1000108431](https://github.com/Bitovn/social-app-issues/assets/136789746/a0968158-6de3-4579-bdef-956575f1dfe8)
I have placed the same padding and alignment same as figma. Although it is not exactly same.
